version: '3.5'
name: 'sprinta'
services:
  db: 
    image: postgres
    restart: always
    container_name: sprinta_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sprinta
    ports:
      - 8011:5432
    volumes:
      - ./db_data:/var/lib/postgresql-data

volumes:
  db_data: